closeio/cleancat

cleancat/base.py, tests/__init__.py
I noticed that calling `external_clean(ExtSchema)` from a `BaseSchema` where `self.orig_data is None` results in `ExtSchema.orig_data == BaseSchema.data`, which is wrong and prevents `ExtSchema` for doing proper validation based on original values.
=> Fix the way orig_data is set during an external clean.

cleancat/base.py, tests/__init__.py
Do not allow spaces and other nonsense in domain part.
Ex: `http:// google.com`
=> Stricter URL check by not allowing arbitrary chars in domain part

cleancat/base.py, tests/__init__.py
Add serialization capabilities so that a schema can be used both for validating input data as well as for returning output data.
This allows keeping both the read and write fields in the schema for a cleaner integration with REST libraries.
Also adds an `Enum` field that can be used in Python 3.4+.
=> Add serialization capabilities

cleancat/base.py, tests/__init__.py
The `Enum` type should return the enumeration member instead of the value. The value is still returned when serializing the data.
=> Return enumeration member in Enum class

circle.yml, cleancat/__init__.py, cleancat/base.py, cleancat/utils.py, requirements.txt, setup.cfg, tests/__init__.py
Adds flake8 to the CI and fixes issues discovered by its run. We ignore `E501` because some lines can be longer than 79 chars without that being a problem.
Motivated primarily by the fact that `MongoEmbeddedReference` defined its `clean` method twice :)
=> Use flake8

cleancat/base.py
Commits can be reviewed separately. The first commit introduces no logical changes. The second one fixes a redundant call to `Dict.clean` (I've confirmed that it was called twice for a single POST/PUT in our API).
=> Clean up MongoEmbeddedReference

.gitignore, cleancat/__init__.py, cleancat/base.py, cleancat/mongo.py, cleancat/sqla.py, requirements.txt, setup.cfg, setup.py, tests/sqla.py
This PR abstracts away common logic of an embedded reference, makes `MongoEmbeddedReference` inherit from it, and adds an `SQLAEmbeddedReference`.
TODOs:
=> EmbeddedReference base class + SQLAEmbeddedReference

cleancat/base.py, tests/__init__.py, tests/mongo.py, tests/sqla.py
Before this PR, serializing an object could fail even if its data was clean. For example, if you had an optional `DateTime` field and tried to serialize `{'dt_field_name': None}`, you'd get `AttributeError: 'NoneType' object has no attribute 'isoformat'`. That's because the overridden `DateTime.serialize` method expects a valid `datetime.datetime` value: https://github.com/closeio/cleancat/blob/48b99263e89e7909d305e8d861e6098fdba6476d/cleancat/base.py#L177-L178
All the other overridden `serialize` methods (e.g. `List.serialize`, `Enum.serialize`, etc.) follow the same pattern. I figured this is an issue we can tackle generically and *never* call `field.serialize(None)`.
An alternative would be to fix the overridden methods by prefixing them all with `if value is None: return`, but I think …
=> Fix serializing None values

cleancat/base.py, tests/__init__.py
The field name coming in (i.e. during the "clean" phase) should be the same as the field name going out (during serialization).
=> Fix raw field name serialization

cleancat/base.py, setup.py, tests/__init__.py
This PR:
* Allows you to only consider a subset of a specific enum's options valid.
* Installs `enum34` in tests so that we can test the `Enum` field in Python v2.
* Is backward-compatible, unless someone initialized `Enum()` using positional arguments (highly unlikely).
=> Allow to narrow down choices in an Enum field

cleancat/base.py, cleancat/mongo.py
`hasattr`'s usage is discouraged because it swallows exceptions, some of which should've bubbled to the surface.
=> Stop using hasattr

cleancat/base.py, setup.cfg
This PR speeds up the `Regex` field (and all fields based on it, i.e. `DateTime`, `Email`, `URL`, and `RelaxedURL`) by caching the compiled regular expression the first time `Regex.clean(...)` is called.
It's worth noting that Python already implements its own caching of regex patterns. [Docs for `re.compile`](https://docs.python.org/3/library/re.html#re.compile) say:
> **Note:** The compiled versions of the most recent patterns passed to `re.compile()` and the module-level matching functions are cached, so programs that use only a few regular expressions at a time needn’t worry about compiling regular expressions. 
That said, on my MBP I still see a consistent difference in performance when running the following code on `master` vs on this branch:
```py
from cleancat import Email
field = …
```
=> Speed up the Regex field

cleancat/base.py, tests/test_base.py
Add a compatibility layer to make error message unchanged when we migrate to Python 3.
=> Compatibility code for external error message in APIs

cleancat/base.py, tests/test_base.py
Related to Python 3.
We can't have a `SortedSet` without a sorting key when comparing objects anymore, since Python 3 is more strict about comparing and sorting objects without an explicit sorting criteria will raise.
=> Let `SortedSet` sort by a given key

cleancat/base.py
`ParserError` only appears in `python-dateutil==2.8.1`, and it's a subclass of `ValueError`.
Checking for `ValueError` is the safest option, will work in both versions because `ParserError` subclasses it.
=> Check for ValueError

cleancat/base.py, tests/test_base.py
Sometimes child schemas need it.
=> Option to preserve type field in PolymorphicField

.circleci/config.yml, .gitignore, cleancat/base.py, setup.cfg, setup.py, tox.ini
This commit removes Python v2.7 and v3.4 from the testing matrix (they have both reached the EOL by now) and also removes some information related to `tox`, which is no longer used in this project.
Once we merge this, we should bump the version to v1.0.0.
=> Drop unused Tox and old Python versions.

.circleci/config.yml, .gitignore, cleancat/base.py, setup.cfg, setup.py, tests/test_base.py, tox.ini
This is useful when e.g. you want the blank value for a string or a boolean to be `None` instead of the default `''`/`False`.
Branched off of https://github.com/closeio/cleancat/pull/58. Review the last commit only.
=> Allow declaring a specific blank value on a per-field basis

cleancat/base.py, tests/test_base.py
Set a default sorting `key` to `SortedSet` when it's based on `Enum` and no `key` is provided, to prevent `.clean()` from failing.
=> Add default key to Enum-based SortedSets

cleancat/base.py, tests/test_base.py
Without this, a `StopValidation` exception bubbles up too far.
=> Fix defaults in complex fields
